Set constrain_package_deps to true in all tox envs.
Without this, the tests fail because we get latest z3c.relationfield 1.1, even though latest Plone 6.1 pins 1.0.

Sample test failure:

```
Error in test test_relation_list_gets_translated (plone.app.multilingual.tests.test_lif.TestLanguageIndependentRelationField.test_relation_list_gets_translated)
Traceback (most recent call last):
  File "/Users/maurits/.pyenv/versions/3.11.7/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Users/maurits/.pyenv/versions/3.11.7/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/Users/maurits/.pyenv/versions/3.11.7/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
  File "/Users/maurits/community/plone-coredev/6.1/src/plone.app.multilingual/src/plone/app/multilingual/tests/test_lif.py", line 222, in test_relation_list_gets_translated
    a_ca = api.translate(self.a_en, "ca")
  File "/Users/maurits/community/plone-coredev/6.1/src/plone.app.multilingual/src/plone/app/multilingual/api.py", line 46, in translate
    manager.add_translation(target_language)
  File "/Users/maurits/community/plone-coredev/6.1/src/plone.app.multilingual/src/plone/app/multilingual/manager.py", line 135, in add_translation
    translated_object = translation_factory(language)
  File "/Users/maurits/community/plone-coredev/6.1/src/plone.app.multilingual/src/plone/app/multilingual/factory.py", line 99, in __call__
    cloner(new_content)
  File "/Users/maurits/community/plone-coredev/6.1/src/plone.app.multilingual/src/plone/app/multilingual/dx/cloner.py", line 26, in __call__
    ILanguageIndependentFieldsManager(self.context).copy_fields(obj)
  File "/Users/maurits/community/plone-coredev/6.1/src/plone.app.multilingual/src/plone/app/multilingual/dx/cloner.py", line 78, in copy_fields
    copied_relation = self.copy_relation(
  File "/Users/maurits/community/plone-coredev/6.1/src/plone.app.multilingual/src/plone/app/multilingual/dx/cloner.py", line 42, in copy_relation
    if not relation_value or relation_value.isBroken():
  File "/Users/maurits/community/plone-coredev/6.1/src/plone.app.multilingual/.tox/test/lib/python3.11/site-packages/z3c/relationfield/relation.py", line 105, in isBroken
    return self.to_id is None or self.from_object is None
  File "/Users/maurits/community/plone-coredev/6.1/src/plone.app.multilingual/.tox/test/lib/python3.11/site-packages/plone/app/relationfield/monkey.py", line 18, in get_from_object
    self._from_id = intids.register(self.__dict__["from_object"])
KeyError: 'from_object'
```

For that KeyError, see https://github.com/plone/plone.app.relationfield/issues/45.

But the issue that the current commit fixes, is that we should be using the proper constraints, instead of getting the latest from PyPI.